### ISSUE TITLE
NameError: uninitialized constant IshareHelper::AdditionalTagsHelper

### ISSUE THREAD

**Issue by gaurav-cointab** [JKeySZR/redmine_ishare#1]
Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.7.3-p183 (2021-04-05) [amd64-freebsd12]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               Mysql2

Steps:
git clone https://github.com/JKeySZR/redmine_ishare.git
bundle install --without development test --no-deployment
bundle exec rake redmine:plugins:migrate RAILS_ENV=production NAME=redmine_ishare

Note: These are the general steps I have been using to install and redmine plugin.

Error:
rake aborted!
NameError: uninitialized constant IshareHelper::AdditionalTagsHelper
/usr/local/www/redmine/plugins/redmine_ishare/app/helpers/ishare_helper.rb:11:in `<module:IshareHelper>'
/usr/local/www/redmine/plugins/redmine_ishare/app/helpers/ishare_helper.rb:9:in `<top (required)>'
/usr/local/www/redmine/plugins/redmine_ishare/lib/redmine_ishare/patches/application_controller_patch.rb:13:in `block in included'
/usr/local/www/redmine/plugins/redmine_ishare/lib/redmine_ishare/patches/application_controller_patch.rb:9:in `class_eval'
/usr/local/www/redmine/plugins/redmine_ishare/lib/redmine_ishare/patches/application_controller_patch.rb:9:in `included'
/usr/local/www/redmine/plugins/redmine_ishare/lib/redmine_ishare/patches/application_controller_patch.rb:78:in `include'
/usr/local/www/redmine/plugins/redmine_ishare/lib/redmine_ishare/patches/application_controller_patch.rb:78:in `<top (required)>'
/usr/local/www/redmine/plugins/redmine_ishare/lib/redmine_ishare.rb:2:in `<top (required)>'
/usr/local/www/redmine/plugins/redmine_ishare/init.rb:48:in `<top (required)>'
/usr/local/www/redmine/lib/redmine/plugin.rb:187:in `block in load'
/usr/local/www/redmine/lib/redmine/plugin.rb:178:in `each'
/usr/local/www/redmine/lib/redmine/plugin.rb:178:in `load'
/usr/local/www/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/usr/local/www/redmine/config/environment.rb:16:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by JKeySZR** [comment]
This is due to a dependency on another plugin. for tags 
I use the plugin from https://github.com/AlphaNodes/additional_tags

I'll try to remove this dependency soon.

**Comment by pravindodia** [comment]
Please update as I cannot use additonal_tags as I am using redmineup_tags and both are not compatible to each other

**Comment by pravindodia** [comment]
> This is due to a dependency on another plugin. for tags I use the plugin from https://github.com/AlphaNodes/additional_tags
> 
> I'll try to remove this dependency soon.

Hello @JKeySZR I am sorry to bother you but do you have any plans to work on it ? I am really interested in this plugin. Please respond.
